# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/arsen/Documents/Year_2/Semester 2/OS/PR2/Shell_final"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/arsen/Documents/Year_2/Semester 2/OS/PR2/Shell_final"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/arsen/Documents/Year_2/Semester 2/OS/PR2/Shell_final/CMakeFiles" "/home/arsen/Documents/Year_2/Semester 2/OS/PR2/Shell_final/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/arsen/Documents/Year_2/Semester 2/OS/PR2/Shell_final/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ls_cpp

# Build rule for target.
ls_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls_cpp
.PHONY : ls_cpp

# fast build rule for target.
ls_cpp/fast:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/build
.PHONY : ls_cpp/fast

#=============================================================================
# Target rules for targets named Shell_cpp

# Build rule for target.
Shell_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Shell_cpp
.PHONY : Shell_cpp

# fast build rule for target.
Shell_cpp/fast:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/build
.PHONY : Shell_cpp/fast

ls.o: ls.cpp.o

.PHONY : ls.o

# target to build an object file
ls.cpp.o:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/ls.cpp.o
.PHONY : ls.cpp.o

ls.i: ls.cpp.i

.PHONY : ls.i

# target to preprocess a source file
ls.cpp.i:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/ls.cpp.i
.PHONY : ls.cpp.i

ls.s: ls.cpp.s

.PHONY : ls.s

# target to generate assembly for a file
ls.cpp.s:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/ls.cpp.s
.PHONY : ls.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/main.cpp.s
.PHONY : main.cpp.s

main_ls.o: main_ls.cpp.o

.PHONY : main_ls.o

# target to build an object file
main_ls.cpp.o:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/main_ls.cpp.o
.PHONY : main_ls.cpp.o

main_ls.i: main_ls.cpp.i

.PHONY : main_ls.i

# target to preprocess a source file
main_ls.cpp.i:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/main_ls.cpp.i
.PHONY : main_ls.cpp.i

main_ls.s: main_ls.cpp.s

.PHONY : main_ls.s

# target to generate assembly for a file
main_ls.cpp.s:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/main_ls.cpp.s
.PHONY : main_ls.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ls_cpp"
	@echo "... Shell_cpp"
	@echo "... ls.o"
	@echo "... ls.i"
	@echo "... ls.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_ls.o"
	@echo "... main_ls.i"
	@echo "... main_ls.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

