# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arsen/Documents/Year_2/Semester_2/OS/PR2/Shell_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arsen/Documents/Year_2/Semester_2/OS/PR2/Shell_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/arsen/Programs/clion-2016.3.4/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arsen/Documents/Year_2/Semester_2/OS/PR2/Shell_cpp/CMakeFiles /home/arsen/Documents/Year_2/Semester_2/OS/PR2/Shell_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arsen/Documents/Year_2/Semester_2/OS/PR2/Shell_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grep_cpp

# Build rule for target.
grep_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grep_cpp
.PHONY : grep_cpp

# fast build rule for target.
grep_cpp/fast:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/build
.PHONY : grep_cpp/fast

#=============================================================================
# Target rules for targets named rm_cpp

# Build rule for target.
rm_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rm_cpp
.PHONY : rm_cpp

# fast build rule for target.
rm_cpp/fast:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/build
.PHONY : rm_cpp/fast

#=============================================================================
# Target rules for targets named mkdir_cpp

# Build rule for target.
mkdir_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mkdir_cpp
.PHONY : mkdir_cpp

# fast build rule for target.
mkdir_cpp/fast:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/build
.PHONY : mkdir_cpp/fast

#=============================================================================
# Target rules for targets named ls_cpp

# Build rule for target.
ls_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ls_cpp
.PHONY : ls_cpp

# fast build rule for target.
ls_cpp/fast:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/build
.PHONY : ls_cpp/fast

#=============================================================================
# Target rules for targets named Shell_cpp

# Build rule for target.
Shell_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Shell_cpp
.PHONY : Shell_cpp

# fast build rule for target.
Shell_cpp/fast:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/build
.PHONY : Shell_cpp/fast

ls.o: ls.cpp.o

.PHONY : ls.o

# target to build an object file
ls.cpp.o:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/ls.cpp.o
.PHONY : ls.cpp.o

ls.i: ls.cpp.i

.PHONY : ls.i

# target to preprocess a source file
ls.cpp.i:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/ls.cpp.i
.PHONY : ls.cpp.i

ls.s: ls.cpp.s

.PHONY : ls.s

# target to generate assembly for a file
ls.cpp.s:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/ls.cpp.s
.PHONY : ls.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/main.cpp.s
.PHONY : main.cpp.s

main_ls.o: main_ls.cpp.o

.PHONY : main_ls.o

# target to build an object file
main_ls.cpp.o:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/main_ls.cpp.o
.PHONY : main_ls.cpp.o

main_ls.i: main_ls.cpp.i

.PHONY : main_ls.i

# target to preprocess a source file
main_ls.cpp.i:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/main_ls.cpp.i
.PHONY : main_ls.cpp.i

main_ls.s: main_ls.cpp.s

.PHONY : main_ls.s

# target to generate assembly for a file
main_ls.cpp.s:
	$(MAKE) -f CMakeFiles/ls_cpp.dir/build.make CMakeFiles/ls_cpp.dir/main_ls.cpp.s
.PHONY : main_ls.cpp.s

main_mkdir.o: main_mkdir.cpp.o

.PHONY : main_mkdir.o

# target to build an object file
main_mkdir.cpp.o:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/main_mkdir.cpp.o
.PHONY : main_mkdir.cpp.o

main_mkdir.i: main_mkdir.cpp.i

.PHONY : main_mkdir.i

# target to preprocess a source file
main_mkdir.cpp.i:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/main_mkdir.cpp.i
.PHONY : main_mkdir.cpp.i

main_mkdir.s: main_mkdir.cpp.s

.PHONY : main_mkdir.s

# target to generate assembly for a file
main_mkdir.cpp.s:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/main_mkdir.cpp.s
.PHONY : main_mkdir.cpp.s

main_mygrep.o: main_mygrep.cpp.o

.PHONY : main_mygrep.o

# target to build an object file
main_mygrep.cpp.o:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/main_mygrep.cpp.o
.PHONY : main_mygrep.cpp.o

main_mygrep.i: main_mygrep.cpp.i

.PHONY : main_mygrep.i

# target to preprocess a source file
main_mygrep.cpp.i:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/main_mygrep.cpp.i
.PHONY : main_mygrep.cpp.i

main_mygrep.s: main_mygrep.cpp.s

.PHONY : main_mygrep.s

# target to generate assembly for a file
main_mygrep.cpp.s:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/main_mygrep.cpp.s
.PHONY : main_mygrep.cpp.s

main_rm.o: main_rm.cpp.o

.PHONY : main_rm.o

# target to build an object file
main_rm.cpp.o:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/main_rm.cpp.o
.PHONY : main_rm.cpp.o

main_rm.i: main_rm.cpp.i

.PHONY : main_rm.i

# target to preprocess a source file
main_rm.cpp.i:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/main_rm.cpp.i
.PHONY : main_rm.cpp.i

main_rm.s: main_rm.cpp.s

.PHONY : main_rm.s

# target to generate assembly for a file
main_rm.cpp.s:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/main_rm.cpp.s
.PHONY : main_rm.cpp.s

mkdir.o: mkdir.cpp.o

.PHONY : mkdir.o

# target to build an object file
mkdir.cpp.o:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/mkdir.cpp.o
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/mkdir.cpp.o
.PHONY : mkdir.cpp.o

mkdir.i: mkdir.cpp.i

.PHONY : mkdir.i

# target to preprocess a source file
mkdir.cpp.i:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/mkdir.cpp.i
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/mkdir.cpp.i
.PHONY : mkdir.cpp.i

mkdir.s: mkdir.cpp.s

.PHONY : mkdir.s

# target to generate assembly for a file
mkdir.cpp.s:
	$(MAKE) -f CMakeFiles/mkdir_cpp.dir/build.make CMakeFiles/mkdir_cpp.dir/mkdir.cpp.s
	$(MAKE) -f CMakeFiles/Shell_cpp.dir/build.make CMakeFiles/Shell_cpp.dir/mkdir.cpp.s
.PHONY : mkdir.cpp.s

mygrep.o: mygrep.cpp.o

.PHONY : mygrep.o

# target to build an object file
mygrep.cpp.o:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/mygrep.cpp.o
.PHONY : mygrep.cpp.o

mygrep.i: mygrep.cpp.i

.PHONY : mygrep.i

# target to preprocess a source file
mygrep.cpp.i:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/mygrep.cpp.i
.PHONY : mygrep.cpp.i

mygrep.s: mygrep.cpp.s

.PHONY : mygrep.s

# target to generate assembly for a file
mygrep.cpp.s:
	$(MAKE) -f CMakeFiles/grep_cpp.dir/build.make CMakeFiles/grep_cpp.dir/mygrep.cpp.s
.PHONY : mygrep.cpp.s

rm.o: rm.cpp.o

.PHONY : rm.o

# target to build an object file
rm.cpp.o:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/rm.cpp.o
.PHONY : rm.cpp.o

rm.i: rm.cpp.i

.PHONY : rm.i

# target to preprocess a source file
rm.cpp.i:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/rm.cpp.i
.PHONY : rm.cpp.i

rm.s: rm.cpp.s

.PHONY : rm.s

# target to generate assembly for a file
rm.cpp.s:
	$(MAKE) -f CMakeFiles/rm_cpp.dir/build.make CMakeFiles/rm_cpp.dir/rm.cpp.s
.PHONY : rm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... grep_cpp"
	@echo "... rm_cpp"
	@echo "... mkdir_cpp"
	@echo "... rebuild_cache"
	@echo "... ls_cpp"
	@echo "... Shell_cpp"
	@echo "... ls.o"
	@echo "... ls.i"
	@echo "... ls.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_ls.o"
	@echo "... main_ls.i"
	@echo "... main_ls.s"
	@echo "... main_mkdir.o"
	@echo "... main_mkdir.i"
	@echo "... main_mkdir.s"
	@echo "... main_mygrep.o"
	@echo "... main_mygrep.i"
	@echo "... main_mygrep.s"
	@echo "... main_rm.o"
	@echo "... main_rm.i"
	@echo "... main_rm.s"
	@echo "... mkdir.o"
	@echo "... mkdir.i"
	@echo "... mkdir.s"
	@echo "... mygrep.o"
	@echo "... mygrep.i"
	@echo "... mygrep.s"
	@echo "... rm.o"
	@echo "... rm.i"
	@echo "... rm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

